/**
 * Wonder Light Adventure - Leave Email Templates
 * Official Sender: Wonder Light Adventure <wonderlightadventure@gmail.com>
 */

export interface LeaveEmailParams {
  employeeName: string;
  leaveType: string;
  startDate: string;
  endDate: string;
  days: number;
  reason: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  reviewerName?: string;
  adminNote?: string;
}

export function generateLeaveEmailHtml({
  employeeName,
  leaveType,
  startDate,
  endDate,
  days,
  reason,
  status,
  reviewerName,
  adminNote,
}: LeaveEmailParams): { subject: string; html: string; text: string } {
  const isApproved = status === 'Approved';

  const subject = isApproved
    ? `Leave Request Approved - Wonderlight Adventure`
    : status === 'Pending'
    ? `New Leave Request Submitted — ${employeeName}`
    : `Leave Request Rejected — Wonderlight Adventure`;

  const formattedLeaveType = leaveType.includes('Leave') ? leaveType : `${leaveType} Leave`;
  const daysText = `${days} ${days === 1 ? 'Day' : 'Days'}`;

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${subject}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #F4F7FB; margin: 0; padding: 0; }
    .wrapper { max-width: 580px; margin: 24px auto; background: #FFFFFF; border-radius: 16px; border: 1px solid #E2E8F0; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.04); }
    .header { background: #071A2F; padding: 26px 24px; text-align: center; border-bottom: 4px solid #168BFF; color: white; }
    .content { padding: 32px 28px; color: #162033; font-size: 15px; line-height: 1.6; }
    .card { background: #F8FAFC; border-left: 4px solid ${isApproved ? '#10B981' : '#EF4444'}; border-radius: 10px; padding: 20px; margin: 20px 0; border-top: 1px solid #E2E8F0; border-right: 1px solid #E2E8F0; border-bottom: 1px solid #E2E8F0; }
    .table-details { width: 100%; font-size: 14px; border-collapse: collapse; }
    .table-details td { padding: 5px 0; }
    .label { color: #64748B; font-weight: 600; width: 150px; }
    .value { color: #0F172A; font-weight: 700; }
    .footer { border-top: 1px solid #E2E8F0; margin-top: 28px; padding-top: 18px; color: #475569; font-size: 14px; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h2 style="margin: 0; color: #18BFFF; font-size: 20px; letter-spacing: 1px;">WONDERLIGHT ADVENTURE</h2>
      <p style="margin: 4px 0 0 0; color: #94A3B8; font-size: 12px;">Employee Leave Management Notification</p>
    </div>
    <div class="content">
      <p style="margin: 0 0 16px;">Dear <strong>${employeeName}</strong>,</p>
      
      <p style="margin: 0 0 20px;">
        This is to inform you that your leave request has been reviewed and <strong style="color: ${isApproved ? '#10B981' : '#EF4444'};">${isApproved ? 'approved' : status.toLowerCase()}</strong> by the management.
      </p>

      <div class="card">
        <h4 style="margin: 0 0 12px 0; color: #071A2F; font-size: 13px; text-transform: uppercase; letter-spacing: 0.8px;">Leave Details</h4>
        <table class="table-details">
          <tr><td class="label">Employee Name:</td><td class="value">${employeeName}</td></tr>
          <tr><td class="label">Leave Type:</td><td class="value">${formattedLeaveType}</td></tr>
          <tr><td class="label">Start Date:</td><td class="value">${startDate}</td></tr>
          <tr><td class="label">End Date:</td><td class="value">${endDate}</td></tr>
          <tr><td class="label">Total Leave Days:</td><td class="value">${daysText}</td></tr>
          <tr><td class="label">Reason:</td><td class="value">${reason}</td></tr>
          ${adminNote ? `<tr><td class="label">Management Note:</td><td class="value" style="color: #168BFF;">${adminNote}</td></tr>` : ''}
        </table>
      </div>

      <p style="margin: 0 0 16px;">
        Please ensure that any pending responsibilities are completed or appropriately handed over before the commencement of your leave.
      </p>

      <p style="margin: 0 0 24px;">
        We wish you a pleasant and productive leave period.
      </p>

      <div class="footer">
        <p style="margin: 0 0 4px 0;">Regards,</p>
        <p style="margin: 0; font-weight: 700; color: #071A2F;">Human Resources Department</p>
        <p style="margin: 0; font-weight: 700; color: #168BFF;">Wonderlight Adventure</p>
        <p style="margin: 4px 0 0 0; font-size: 12px; color: #64748B;">Travel • Explore • Experience</p>
      </div>

      <p style="margin: 24px 0 0 0; font-size: 11px; color: #94A3B8; font-style: italic; border-top: 1px stroke #E2E8F0; padding-top: 12px;">
        *This is an automated notification generated by the Wonderlight Adventure Employee Management System.*
      </p>
    </div>
  </div>
</body>
</html>
  `.trim();

  const text = `
Dear ${employeeName},

This is to inform you that your leave request has been reviewed and ${isApproved ? 'approved' : status.toLowerCase()} by the management.

Leave Details
Employee Name: ${employeeName}
Leave Type: ${formattedLeaveType}
Start Date: ${startDate}
End Date: ${endDate}
Total Leave Days: ${daysText}
Reason: ${reason}
${adminNote ? `Management Note: ${adminNote}\n` : ''}
Please ensure that any pending responsibilities are completed or appropriately handed over before the commencement of your leave.

We wish you a pleasant and productive leave period.

Regards,
Human Resources Department
Wonderlight Adventure
Travel • Explore • Experience

*This is an automated notification generated by the Wonderlight Adventure Employee Management System.*
  `.trim();

  return { subject, html, text };
}

